insert into equipes(nom,commune,stade) values ('Angers SCO', ' ', ' '),
('AS Monaco', ' ', ' '),
('SC Bastia', ' ', ' '),
('Stade de Reims', ' ', ' '),
('Toulouse FC', ' ', ' '),
('FC Nantes', ' ', ' '),
('Paris SG', ' ', ' '),
('SM Caen', ' ', ' '),
('ESTAC Troyes', ' ', ' '),
('FC Lorient', ' ', ' '),
('GFC Ajaccio', ' ', ' '),
('Lyon', ' ', ' '),
('AS Saint-Etienne', ' ', ' '),
('Bordeaux', ' ', ' '),
('OGC Nice', ' ', ' '),
('Stade Rennais', ' ', ' '),
('EA Guingamp', ' ', ' '),
('LOSC Lille', ' ', ' '),
('Marseille', ' ', ' '),
('Montpellier HSC', ' ', ' ');

